--------------------------------------------------------
-- Archivo creado  - viernes-abril-04-2014   
--------------------------------------------------------
DROP TABLE "REFERENCIA"."TPRY_TIPO_CONTRATO" cascade constraints;
--------------------------------------------------------
--  DDL for Table TPRY_TIPO_CONTRATO
--------------------------------------------------------

  CREATE TABLE "REFERENCIA"."TPRY_TIPO_CONTRATO" 
   (	"TCTO_ID" NUMBER, 
	"TCTO_NOMBRE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
REM INSERTING into REFERENCIA.TPRY_TIPO_CONTRATO
SET DEFINE OFF;
Insert into REFERENCIA.TPRY_TIPO_CONTRATO (TCTO_ID,TCTO_NOMBRE) values (1,'Contrato de Obra');
Insert into REFERENCIA.TPRY_TIPO_CONTRATO (TCTO_ID,TCTO_NOMBRE) values (2,'Contrato de Servicio');
--------------------------------------------------------
--  DDL for Index TGENTIPOCONTRATO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "REFERENCIA"."TGENTIPOCONTRATO_PK" ON "REFERENCIA"."TPRY_TIPO_CONTRATO" ("TCTO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table TPRY_TIPO_CONTRATO
--------------------------------------------------------

  ALTER TABLE "REFERENCIA"."TPRY_TIPO_CONTRATO" ADD CONSTRAINT "PK01_TCTO_ID" PRIMARY KEY ("TCTO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "REFERENCIA"."TPRY_TIPO_CONTRATO" MODIFY ("TCTO_ID" NOT NULL ENABLE);
