--------------------------------------------------------
-- Archivo creado  - viernes-abril-04-2014   
--------------------------------------------------------
DROP TABLE "REFERENCIA"."TPRY_CONTRATOS" cascade constraints;
DROP TABLE "REFERENCIA"."TPRY_DOCS_OFICIALES" cascade constraints;
DROP TABLE "REFERENCIA"."TPRY_ESTATUS_CONTRATO" cascade constraints;
DROP TABLE "REFERENCIA"."TPRY_PROVEEDORES" cascade constraints;
DROP TABLE "REFERENCIA"."TPRY_PROYECTOS" cascade constraints;
DROP TABLE "REFERENCIA"."TPRY_TIPO_CONTRATO" cascade constraints;
--------------------------------------------------------
--  DDL for Table TPRY_CONTRATOS
--------------------------------------------------------

  CREATE TABLE "REFERENCIA"."TPRY_CONTRATOS" 
   (	"CTTO_ID" NUMBER, 
	"CTTO_FOLIO" VARCHAR2(20 BYTE), 
	"CTTO_FECHA_CREACION" DATE, 
	"PRYC_ID" NUMBER(*,0), 
	"TCTO_ID" NUMBER(*,0), 
	"DCTO_ID" NUMBER(*,0), 
	"PROV_ID" NUMBER(*,0), 
	"CTTO_PREFOLIO" NUMBER, 
	"CTTO_MONTO" NUMBER, 
	"ECTO_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table TPRY_DOCS_OFICIALES
--------------------------------------------------------

  CREATE TABLE "REFERENCIA"."TPRY_DOCS_OFICIALES" 
   (	"DOCS_ID" NUMBER, 
	"DOCS_FOLIO" VARCHAR2(50 BYTE), 
	"EMPR_ID" VARCHAR2(5 BYTE), 
	"DOCS_FECHA_ELABORACION" TIMESTAMP (6), 
	"TDOC_ID" NUMBER(*,0), 
	"PROV_ID" NUMBER(*,0), 
	"DOCS_DIRIGIDOA" VARCHAR2(80 BYTE), 
	"PROY_ID" NUMBER(*,0), 
	"RESP_ID" NUMBER(*,0), 
	"DOCS_OBSERVACIONES" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table TPRY_ESTATUS_CONTRATO
--------------------------------------------------------

  CREATE TABLE "REFERENCIA"."TPRY_ESTATUS_CONTRATO" 
   (	"ECTO_ID" NUMBER, 
	"ECTO_ESTATUS" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table TPRY_PROVEEDORES
--------------------------------------------------------

  CREATE TABLE "REFERENCIA"."TPRY_PROVEEDORES" 
   (	"PROV_ID" NUMBER, 
	"PROV_RAZON_SOCIAL" VARCHAR2(100 BYTE), 
	"PROV_DOM_FISCAL" VARCHAR2(200 BYTE), 
	"PROV_DOM_CORRESP" VARCHAR2(200 BYTE), 
	"PROV_REGISTRO_ABAST" NUMBER, 
	"PROV_REGISTRO_PROY" NUMBER, 
	"ZPRO_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table TPRY_PROYECTOS
--------------------------------------------------------

  CREATE TABLE "REFERENCIA"."TPRY_PROYECTOS" 
   (	"PROY_ID" NUMBER, 
	"PROY_CARPETA" NUMBER, 
	"EMPR_ID" VARCHAR2(5 BYTE), 
	"PROY_NOMBRE" VARCHAR2(400 BYTE), 
	"PROY_NOMBRE_CORTO" VARCHAR2(200 BYTE), 
	"TOBR_ID" NUMBER, 
	"ORGP_ID" NUMBER, 
	"DIVP_ID" NUMBER, 
	"PROY_FECHA_RECEP_INF" TIMESTAMP (6), 
	"PROY_PRESUPUESTO" NUMBER, 
	"PROY_ELEMENTO_PEP" VARCHAR2(20 BYTE), 
	"PROY_CENTRO_COSTOS" VARCHAR2(200 BYTE), 
	"PROY_SOL_INVERSION" VARCHAR2(1 BYTE), 
	"PROY_FECH_ENTREGA_SAI" TIMESTAMP (6), 
	"PROY_SOLICITUD_SAP" NUMBER, 
	"PROY_FECH_INICIO_ESTIMADO" TIMESTAMP (6), 
	"PROY_FECH_FIN_ESTIMADO" TIMESTAMP (6), 
	"PROY_DURACION_PROY" NUMBER, 
	"PROY_FECH_INICIO_REAL" TIMESTAMP (6), 
	"PROY_FECH_FIN_REAL" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table TPRY_TIPO_CONTRATO
--------------------------------------------------------

  CREATE TABLE "REFERENCIA"."TPRY_TIPO_CONTRATO" 
   (	"TCTO_ID" NUMBER, 
	"TCTO_NOMBRE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
REM INSERTING into REFERENCIA.TPRY_CONTRATOS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index TPRY_CONTRATOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "REFERENCIA"."TPRY_CONTRATOS_PK" ON "REFERENCIA"."TPRY_CONTRATOS" ("CTTO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table TPRY_CONTRATOS
--------------------------------------------------------

  ALTER TABLE "REFERENCIA"."TPRY_CONTRATOS" ADD CONSTRAINT "PK01_CTTO_ID" PRIMARY KEY ("CTTO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "REFERENCIA"."TPRY_CONTRATOS" MODIFY ("CTTO_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table TPRY_CONTRATOS
--------------------------------------------------------

  ALTER TABLE "REFERENCIA"."TPRY_CONTRATOS" ADD CONSTRAINT "FK01_CTTO_TCTO_ID" FOREIGN KEY ("TCTO_ID")
	  REFERENCES "REFERENCIA"."TPRY_TIPO_CONTRATO" ("TCTO_ID") ENABLE;
  ALTER TABLE "REFERENCIA"."TPRY_CONTRATOS" ADD CONSTRAINT "FK02_CTTO_DOCS_ID" FOREIGN KEY ("DCTO_ID")
	  REFERENCES "REFERENCIA"."TPRY_DOCS_OFICIALES" ("DOCS_ID") ENABLE;
  ALTER TABLE "REFERENCIA"."TPRY_CONTRATOS" ADD CONSTRAINT "FK03_CTTO_ECTO_ID" FOREIGN KEY ("ECTO_ID")
	  REFERENCES "REFERENCIA"."TPRY_ESTATUS_CONTRATO" ("ECTO_ID") ENABLE;
  ALTER TABLE "REFERENCIA"."TPRY_CONTRATOS" ADD CONSTRAINT "FK04_CTTO_PRYC_ID" FOREIGN KEY ("PRYC_ID")
	  REFERENCES "REFERENCIA"."TPRY_PROYECTOS" ("PROY_ID") ENABLE;
  ALTER TABLE "REFERENCIA"."TPRY_CONTRATOS" ADD CONSTRAINT "FK05_CTTO_PROV_ID" FOREIGN KEY ("PROV_ID")
	  REFERENCES "REFERENCIA"."TPRY_PROVEEDORES" ("PROV_ID") ENABLE;
