--------------------------------------------------------
-- Archivo creado  - viernes-abril-04-2014   
--------------------------------------------------------
DROP TABLE "REFERENCIA"."TPRY_PROYECTOS" cascade constraints;
DROP TABLE "REFERENCIA"."TPRY_DIVISION" cascade constraints;
DROP TABLE "REFERENCIA"."TPRY_EMPRESA" cascade constraints;
DROP TABLE "REFERENCIA"."TPRY_ORIGEN_PROYECTO" cascade constraints;
DROP TABLE "REFERENCIA"."TPRY_TIPO_OBRA" cascade constraints;
--------------------------------------------------------
--  DDL for Table TPRY_PROYECTOS
--------------------------------------------------------

  CREATE TABLE "REFERENCIA"."TPRY_PROYECTOS" 
   (	"PROY_ID" NUMBER, 
	"PROY_CARPETA" NUMBER, 
	"EMPR_ID" VARCHAR2(5 BYTE), 
	"PROY_NOMBRE" VARCHAR2(400 BYTE), 
	"PROY_NOMBRE_CORTO" VARCHAR2(200 BYTE), 
	"TOBR_ID" NUMBER, 
	"ORGP_ID" NUMBER, 
	"DIVP_ID" NUMBER, 
	"PROY_FECHA_RECEP_INF" TIMESTAMP (6), 
	"PROY_PRESUPUESTO" NUMBER, 
	"PROY_ELEMENTO_PEP" VARCHAR2(20 BYTE), 
	"PROY_CENTRO_COSTOS" VARCHAR2(200 BYTE), 
	"PROY_SOL_INVERSION" VARCHAR2(1 BYTE), 
	"PROY_FECH_ENTREGA_SAI" TIMESTAMP (6), 
	"PROY_SOLICITUD_SAP" NUMBER, 
	"PROY_FECH_INICIO_ESTIMADO" TIMESTAMP (6), 
	"PROY_FECH_FIN_ESTIMADO" TIMESTAMP (6), 
	"PROY_DURACION_PROY" NUMBER, 
	"PROY_FECH_INICIO_REAL" TIMESTAMP (6), 
	"PROY_FECH_FIN_REAL" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table TPRY_DIVISION
--------------------------------------------------------

  CREATE TABLE "REFERENCIA"."TPRY_DIVISION" 
   (	"DIVS_ID" NUMBER, 
	"DIVS_NOMBRE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table TPRY_EMPRESA
--------------------------------------------------------

  CREATE TABLE "REFERENCIA"."TPRY_EMPRESA" 
   (	"EMPR_ID" VARCHAR2(5 BYTE), 
	"EMPR_NOMBRE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table TPRY_ORIGEN_PROYECTO
--------------------------------------------------------

  CREATE TABLE "REFERENCIA"."TPRY_ORIGEN_PROYECTO" 
   (	"OPRY_ID" NUMBER, 
	"OPRY_NOMBRE" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table TPRY_TIPO_OBRA
--------------------------------------------------------

  CREATE TABLE "REFERENCIA"."TPRY_TIPO_OBRA" 
   (	"TOBR_ID" NUMBER, 
	"TOBR_OBRA" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
REM INSERTING into REFERENCIA.TPRY_PROYECTOS
SET DEFINE OFF;
Insert into REFERENCIA.TPRY_PROYECTOS (PROY_ID,PROY_CARPETA,EMPR_ID,PROY_NOMBRE,PROY_NOMBRE_CORTO,TOBR_ID,ORGP_ID,DIVP_ID,PROY_FECHA_RECEP_INF,PROY_PRESUPUESTO,PROY_ELEMENTO_PEP,PROY_CENTRO_COSTOS,PROY_SOL_INVERSION,PROY_FECH_ENTREGA_SAI,PROY_SOLICITUD_SAP,PROY_FECH_INICIO_ESTIMADO,PROY_FECH_FIN_ESTIMADO,PROY_DURACION_PROY,PROY_FECH_INICIO_REAL,PROY_FECH_FIN_REAL) values (4,1,'FSRR','PROYECTO DOS Y DOS','cuatro',5,1,2,to_timestamp('05/04/14 00:00:00.000000000','DD/MM/RR HH24:MI:SS.FF'),12000,'44-55-44-22-33-0-7-4','SDERF3456','Y',to_timestamp('05/04/14 00:00:00.000000000','DD/MM/RR HH24:MI:SS.FF'),45678999,to_timestamp('05/04/14 00:00:00.000000000','DD/MM/RR HH24:MI:SS.FF'),to_timestamp('05/04/14 00:00:00.000000000','DD/MM/RR HH24:MI:SS.FF'),4,to_timestamp('05/04/14 00:00:00.000000000','DD/MM/RR HH24:MI:SS.FF'),to_timestamp('05/04/14 00:00:00.000000000','DD/MM/RR HH24:MI:SS.FF'));
Insert into REFERENCIA.TPRY_PROYECTOS (PROY_ID,PROY_CARPETA,EMPR_ID,PROY_NOMBRE,PROY_NOMBRE_CORTO,TOBR_ID,ORGP_ID,DIVP_ID,PROY_FECHA_RECEP_INF,PROY_PRESUPUESTO,PROY_ELEMENTO_PEP,PROY_CENTRO_COSTOS,PROY_SOL_INVERSION,PROY_FECH_ENTREGA_SAI,PROY_SOLICITUD_SAP,PROY_FECH_INICIO_ESTIMADO,PROY_FECH_FIN_ESTIMADO,PROY_DURACION_PROY,PROY_FECH_INICIO_REAL,PROY_FECH_FIN_REAL) values (5,2,'FXE','PROYECTO DOS Y TRES','cinco',3,3,3,to_timestamp('05/04/14 00:00:00.000000000','DD/MM/RR HH24:MI:SS.FF'),12000,'44-55-44-22-33-0-7-4','SDERF3456','N',to_timestamp('05/04/14 00:00:00.000000000','DD/MM/RR HH24:MI:SS.FF'),45678999,to_timestamp('05/04/14 00:00:00.000000000','DD/MM/RR HH24:MI:SS.FF'),to_timestamp('05/04/14 00:00:00.000000000','DD/MM/RR HH24:MI:SS.FF'),6,to_timestamp('05/04/14 00:00:00.000000000','DD/MM/RR HH24:MI:SS.FF'),to_timestamp('05/04/14 00:00:00.000000000','DD/MM/RR HH24:MI:SS.FF'));
Insert into REFERENCIA.TPRY_PROYECTOS (PROY_ID,PROY_CARPETA,EMPR_ID,PROY_NOMBRE,PROY_NOMBRE_CORTO,TOBR_ID,ORGP_ID,DIVP_ID,PROY_FECHA_RECEP_INF,PROY_PRESUPUESTO,PROY_ELEMENTO_PEP,PROY_CENTRO_COSTOS,PROY_SOL_INVERSION,PROY_FECH_ENTREGA_SAI,PROY_SOLICITUD_SAP,PROY_FECH_INICIO_ESTIMADO,PROY_FECH_FIN_ESTIMADO,PROY_DURACION_PROY,PROY_FECH_INICIO_REAL,PROY_FECH_FIN_REAL) values (6,3,'FXE','PROYECTO DOS Y CUATRO','seis',3,2,5,to_timestamp('05/04/14 00:00:00.000000000','DD/MM/RR HH24:MI:SS.FF'),12000,'44-55-44-22-33-0-7-4','SDERF3456','N',to_timestamp('05/04/14 00:00:00.000000000','DD/MM/RR HH24:MI:SS.FF'),45678999,to_timestamp('05/04/14 00:00:00.000000000','DD/MM/RR HH24:MI:SS.FF'),to_timestamp('05/04/14 00:00:00.000000000','DD/MM/RR HH24:MI:SS.FF'),4,to_timestamp('05/04/14 00:00:00.000000000','DD/MM/RR HH24:MI:SS.FF'),to_timestamp('05/04/14 00:00:00.000000000','DD/MM/RR HH24:MI:SS.FF'));
--------------------------------------------------------
--  DDL for Index TPRY_PROYECTOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "REFERENCIA"."TPRY_PROYECTOS_PK" ON "REFERENCIA"."TPRY_PROYECTOS" ("PROY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table TPRY_PROYECTOS
--------------------------------------------------------

  ALTER TABLE "REFERENCIA"."TPRY_PROYECTOS" ADD CONSTRAINT "PK01_PROY_ID" PRIMARY KEY ("PROY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "REFERENCIA"."TPRY_PROYECTOS" MODIFY ("PROY_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table TPRY_PROYECTOS
--------------------------------------------------------

  ALTER TABLE "REFERENCIA"."TPRY_PROYECTOS" ADD CONSTRAINT "FK01_PROY_TOBR_ID" FOREIGN KEY ("TOBR_ID")
	  REFERENCES "REFERENCIA"."TPRY_TIPO_OBRA" ("TOBR_ID") ENABLE;
  ALTER TABLE "REFERENCIA"."TPRY_PROYECTOS" ADD CONSTRAINT "FK02_PROY_EMPR_ID" FOREIGN KEY ("EMPR_ID")
	  REFERENCES "REFERENCIA"."TPRY_EMPRESA" ("EMPR_ID") ENABLE;
  ALTER TABLE "REFERENCIA"."TPRY_PROYECTOS" ADD CONSTRAINT "FK03_PROY_DIVP_ID" FOREIGN KEY ("DIVP_ID")
	  REFERENCES "REFERENCIA"."TPRY_DIVISION" ("DIVS_ID") ENABLE;
  ALTER TABLE "REFERENCIA"."TPRY_PROYECTOS" ADD CONSTRAINT "FK04_PROY_ORGP_ID" FOREIGN KEY ("ORGP_ID")
	  REFERENCES "REFERENCIA"."TPRY_ORIGEN_PROYECTO" ("OPRY_ID") ENABLE;
