--------------------------------------------------------
-- Archivo creado  - viernes-abril-04-2014   
--------------------------------------------------------
DROP TABLE "REFERENCIA"."TPRY_PROVEEDORES" cascade constraints;
DROP TABLE "REFERENCIA"."TPRY_ZONA_PROVEEDOR" cascade constraints;
--------------------------------------------------------
--  DDL for Table TPRY_PROVEEDORES
--------------------------------------------------------

  CREATE TABLE "REFERENCIA"."TPRY_PROVEEDORES" 
   (	"PROV_ID" NUMBER, 
	"PROV_RAZON_SOCIAL" VARCHAR2(100 BYTE), 
	"PROV_DOM_FISCAL" VARCHAR2(200 BYTE), 
	"PROV_DOM_CORRESP" VARCHAR2(200 BYTE), 
	"PROV_REGISTRO_ABAST" NUMBER, 
	"PROV_REGISTRO_PROY" NUMBER, 
	"ZPRO_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table TPRY_ZONA_PROVEEDOR
--------------------------------------------------------

  CREATE TABLE "REFERENCIA"."TPRY_ZONA_PROVEEDOR" 
   (	"ZPRO_ID" NUMBER, 
	"ZPRO_ZONA" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
REM INSERTING into REFERENCIA.TPRY_PROVEEDORES
SET DEFINE OFF;
Insert into REFERENCIA.TPRY_PROVEEDORES (PROV_ID,PROV_RAZON_SOCIAL,PROV_DOM_FISCAL,PROV_DOM_CORRESP,PROV_REGISTRO_ABAST,PROV_REGISTRO_PROY,ZPRO_ID) values (87,'PATO MAS FEO','Ciruelos','Santa Fe',88754578,678987678,4);
Insert into REFERENCIA.TPRY_PROVEEDORES (PROV_ID,PROV_RAZON_SOCIAL,PROV_DOM_FISCAL,PROV_DOM_CORRESP,PROV_REGISTRO_ABAST,PROV_REGISTRO_PROY,ZPRO_ID) values (91,'PROVEEDOR E','sevillae','tlalpane',396543311,954348811,8);
Insert into REFERENCIA.TPRY_PROVEEDORES (PROV_ID,PROV_RAZON_SOCIAL,PROV_DOM_FISCAL,PROV_DOM_CORRESP,PROV_REGISTRO_ABAST,PROV_REGISTRO_PROY,ZPRO_ID) values (86,'PATITO FEO','Reforma 1801','Sevilla 441',89988981,88766661,6);
--------------------------------------------------------
--  DDL for Index TPRY_PROVEEDORES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "REFERENCIA"."TPRY_PROVEEDORES_PK" ON "REFERENCIA"."TPRY_PROVEEDORES" ("PROV_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table TPRY_PROVEEDORES
--------------------------------------------------------

  ALTER TABLE "REFERENCIA"."TPRY_PROVEEDORES" MODIFY ("PROV_RAZON_SOCIAL" NOT NULL ENABLE);
  ALTER TABLE "REFERENCIA"."TPRY_PROVEEDORES" ADD CONSTRAINT "PK01_PROV_ID" PRIMARY KEY ("PROV_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "REFERENCIA"."TPRY_PROVEEDORES" MODIFY ("PROV_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table TPRY_PROVEEDORES
--------------------------------------------------------

  ALTER TABLE "REFERENCIA"."TPRY_PROVEEDORES" ADD CONSTRAINT "FK01_PROV_ZPRO_ID" FOREIGN KEY ("ZPRO_ID")
	  REFERENCES "REFERENCIA"."TPRY_ZONA_PROVEEDOR" ("ZPRO_ID") ENABLE;
