--------------------------------------------------------
-- Archivo creado  - viernes-abril-04-2014   
--------------------------------------------------------
DROP TABLE "REFERENCIA"."TPRY_ZONA_PROVEEDOR" cascade constraints;
--------------------------------------------------------
--  DDL for Table TPRY_ZONA_PROVEEDOR
--------------------------------------------------------

  CREATE TABLE "REFERENCIA"."TPRY_ZONA_PROVEEDOR" 
   (	"ZPRO_ID" NUMBER, 
	"ZPRO_ZONA" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
REM INSERTING into REFERENCIA.TPRY_ZONA_PROVEEDOR
SET DEFINE OFF;
Insert into REFERENCIA.TPRY_ZONA_PROVEEDOR (ZPRO_ID,ZPRO_ZONA) values (1,'Guadalajara');
Insert into REFERENCIA.TPRY_ZONA_PROVEEDOR (ZPRO_ID,ZPRO_ZONA) values (2,'Veracruz');
Insert into REFERENCIA.TPRY_ZONA_PROVEEDOR (ZPRO_ID,ZPRO_ZONA) values (3,'Distrito Federal');
Insert into REFERENCIA.TPRY_ZONA_PROVEEDOR (ZPRO_ID,ZPRO_ZONA) values (4,'Monterrey');
Insert into REFERENCIA.TPRY_ZONA_PROVEEDOR (ZPRO_ID,ZPRO_ZONA) values (5,'Coahuila');
Insert into REFERENCIA.TPRY_ZONA_PROVEEDOR (ZPRO_ID,ZPRO_ZONA) values (6,'Estado de Mexico');
Insert into REFERENCIA.TPRY_ZONA_PROVEEDOR (ZPRO_ID,ZPRO_ZONA) values (7,'Chihuahua');
Insert into REFERENCIA.TPRY_ZONA_PROVEEDOR (ZPRO_ID,ZPRO_ZONA) values (8,'Aguascalientes');
Insert into REFERENCIA.TPRY_ZONA_PROVEEDOR (ZPRO_ID,ZPRO_ZONA) values (9,'Hermosillo');
Insert into REFERENCIA.TPRY_ZONA_PROVEEDOR (ZPRO_ID,ZPRO_ZONA) values (10,'Puebla');
Insert into REFERENCIA.TPRY_ZONA_PROVEEDOR (ZPRO_ID,ZPRO_ZONA) values (11,'Sonora');
Insert into REFERENCIA.TPRY_ZONA_PROVEEDOR (ZPRO_ID,ZPRO_ZONA) values (12,'Queretaro');
Insert into REFERENCIA.TPRY_ZONA_PROVEEDOR (ZPRO_ID,ZPRO_ZONA) values (13,'Tamaulipas');
Insert into REFERENCIA.TPRY_ZONA_PROVEEDOR (ZPRO_ID,ZPRO_ZONA) values (14,'Xalapa');
Insert into REFERENCIA.TPRY_ZONA_PROVEEDOR (ZPRO_ID,ZPRO_ZONA) values (15,'Mexicali');
Insert into REFERENCIA.TPRY_ZONA_PROVEEDOR (ZPRO_ID,ZPRO_ZONA) values (16,'Guanajuato');
Insert into REFERENCIA.TPRY_ZONA_PROVEEDOR (ZPRO_ID,ZPRO_ZONA) values (17,'Queretaro');
--------------------------------------------------------
--  DDL for Index TGEN_ZONA_PROVEEDOR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "REFERENCIA"."TGEN_ZONA_PROVEEDOR_PK" ON "REFERENCIA"."TPRY_ZONA_PROVEEDOR" ("ZPRO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table TPRY_ZONA_PROVEEDOR
--------------------------------------------------------

  ALTER TABLE "REFERENCIA"."TPRY_ZONA_PROVEEDOR" ADD CONSTRAINT "PK01_ZPRO_ID" PRIMARY KEY ("ZPRO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "REFERENCIA"."TPRY_ZONA_PROVEEDOR" MODIFY ("ZPRO_ZONA" NOT NULL ENABLE);
  ALTER TABLE "REFERENCIA"."TPRY_ZONA_PROVEEDOR" MODIFY ("ZPRO_ID" NOT NULL ENABLE);
