--------------------------------------------------------
-- Archivo creado  - miércoles-abril-23-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TPRY_CONCURSOS
--------------------------------------------------------

  CREATE TABLE "REFERENCIA"."TPRY_CONCURSOS" 
   (	"CONC_ID" NUMBER, 
	"PROY_ID" NUMBER, 
	"TCON_ID" NUMBER, 
	"CONC_REAL_INVITACION" DATE, 
	"CONC_REAL_VISITA_OBRA" DATE, 
	"CONC_REAL_PREGUNTAS" DATE, 
	"CONC_REAL_RESPUESTAS" DATE, 
	"CONC_REAL_PROPUESTAS" DATE, 
	"CONC_REAL_REVISION_TEC" DATE, 
	"CONC_REAL_CHECKLIST_TEC" DATE, 
	"CONC_REAL_CARTA_INTENCION" DATE, 
	"CONC_PRECIOS_COMPETITIVOS" VARCHAR2(2 BYTE), 
	"CONC_EN_PRESUPUESTO" VARCHAR2(2 BYTE), 
	"CONC_REVISION_PRECIOS" DATE, 
	"CONC_REVISION_CATALOGO" DATE, 
	"CONC_NOTIF_GANADOR" DATE, 
	"CONC_VOBO_GANADOR" DATE, 
	"PROY_CARPETA" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
REM INSERTING into REFERENCIA.TPRY_CONCURSOS
SET DEFINE OFF;
Insert into REFERENCIA.TPRY_CONCURSOS (CONC_ID,PROY_ID,TCON_ID,CONC_REAL_INVITACION,CONC_REAL_VISITA_OBRA,CONC_REAL_PREGUNTAS,CONC_REAL_RESPUESTAS,CONC_REAL_PROPUESTAS,CONC_REAL_REVISION_TEC,CONC_REAL_CHECKLIST_TEC,CONC_REAL_CARTA_INTENCION,CONC_PRECIOS_COMPETITIVOS,CONC_EN_PRESUPUESTO,CONC_REVISION_PRECIOS,CONC_REVISION_CATALOGO,CONC_NOTIF_GANADOR,CONC_VOBO_GANADOR,PROY_CARPETA) values (28,33,2,to_date('10/02/14','DD/MM/RR'),to_date('10/02/14','DD/MM/RR'),to_date('10/02/14','DD/MM/RR'),to_date('10/02/14','DD/MM/RR'),to_date('10/02/14','DD/MM/RR'),to_date('10/02/14','DD/MM/RR'),to_date('10/02/14','DD/MM/RR'),to_date('10/02/14','DD/MM/RR'),'N','Y',to_date('10/02/14','DD/MM/RR'),to_date('10/02/14','DD/MM/RR'),to_date('10/02/14','DD/MM/RR'),to_date('10/02/14','DD/MM/RR'),21);
--------------------------------------------------------
--  DDL for Index TPRY_CONCURSOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "REFERENCIA"."TPRY_CONCURSOS_PK" ON "REFERENCIA"."TPRY_CONCURSOS" ("CONC_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table TPRY_CONCURSOS
--------------------------------------------------------

  ALTER TABLE "REFERENCIA"."TPRY_CONCURSOS" ADD CONSTRAINT "PK01_TPRY_CONCURSOS_CONC_ID" PRIMARY KEY ("CONC_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "REFERENCIA"."TPRY_CONCURSOS" MODIFY ("CONC_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table TPRY_CONCURSOS
--------------------------------------------------------

  ALTER TABLE "REFERENCIA"."TPRY_CONCURSOS" ADD CONSTRAINT "FK01_TPRY_CONCURSOS_PROY_ID" FOREIGN KEY ("PROY_ID")
	  REFERENCES "REFERENCIA"."TPRY_PROYECTOS" ("PROY_ID") ENABLE;
  ALTER TABLE "REFERENCIA"."TPRY_CONCURSOS" ADD CONSTRAINT "FK02_TPRY_CONCURSOS_TCON_ID" FOREIGN KEY ("TCON_ID")
	  REFERENCES "REFERENCIA"."TPRY_TIPO_CONCURSO" ("TCON_ID") ENABLE;
