--------------------------------------------------------
-- Archivo creado  - viernes-abril-04-2014   
--------------------------------------------------------
DROP TABLE "REFERENCIA"."TPRY_CONTACTO_PROVEEDOR" cascade constraints;
DROP TABLE "REFERENCIA"."TPRY_PROVEEDORES" cascade constraints;
--------------------------------------------------------
--  DDL for Table TPRY_CONTACTO_PROVEEDOR
--------------------------------------------------------

  CREATE TABLE "REFERENCIA"."TPRY_CONTACTO_PROVEEDOR" 
   (	"CTOP_ID" NUMBER, 
	"PROV_ID" NUMBER, 
	"CTOP_NOMBRE" VARCHAR2(50 BYTE), 
	"CTOP_APPATERNO" VARCHAR2(50 BYTE), 
	"CTOP_APMATERNO" VARCHAR2(50 BYTE), 
	"CTOP_EMAIL" VARCHAR2(50 BYTE), 
	"CTOP_TELOFICINA" VARCHAR2(10 BYTE), 
	"CTOP_MOVIL1" VARCHAR2(13 BYTE), 
	"CTOP_MOVIL2" VARCHAR2(13 BYTE), 
	"CTOP_PRINCIPAL" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table TPRY_PROVEEDORES
--------------------------------------------------------

  CREATE TABLE "REFERENCIA"."TPRY_PROVEEDORES" 
   (	"PROV_ID" NUMBER, 
	"PROV_RAZON_SOCIAL" VARCHAR2(100 BYTE), 
	"PROV_DOM_FISCAL" VARCHAR2(200 BYTE), 
	"PROV_DOM_CORRESP" VARCHAR2(200 BYTE), 
	"PROV_REGISTRO_ABAST" NUMBER, 
	"PROV_REGISTRO_PROY" NUMBER, 
	"ZPRO_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
REM INSERTING into REFERENCIA.TPRY_CONTACTO_PROVEEDOR
SET DEFINE OFF;
Insert into REFERENCIA.TPRY_CONTACTO_PROVEEDOR (CTOP_ID,PROV_ID,CTOP_NOMBRE,CTOP_APPATERNO,CTOP_APMATERNO,CTOP_EMAIL,CTOP_TELOFICINA,CTOP_MOVIL1,CTOP_MOVIL2,CTOP_PRINCIPAL) values (90,87,'proveedor','ap paterno e','am materno e','pf@prueba.com','5689909911','6789098711','656789911','Y');
Insert into REFERENCIA.TPRY_CONTACTO_PROVEEDOR (CTOP_ID,PROV_ID,CTOP_NOMBRE,CTOP_APPATERNO,CTOP_APMATERNO,CTOP_EMAIL,CTOP_TELOFICINA,CTOP_MOVIL1,CTOP_MOVIL2,CTOP_PRINCIPAL) values (88,86,'Primero','ap primero','am primero','primero@com','567890098','67890987','7809877890','Y');
--------------------------------------------------------
--  DDL for Index TPRY_CONTACTOSPROVEEDOR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "REFERENCIA"."TPRY_CONTACTOSPROVEEDOR_PK" ON "REFERENCIA"."TPRY_CONTACTO_PROVEEDOR" ("CTOP_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table TPRY_CONTACTO_PROVEEDOR
--------------------------------------------------------

  ALTER TABLE "REFERENCIA"."TPRY_CONTACTO_PROVEEDOR" MODIFY ("PROV_ID" NOT NULL ENABLE);
  ALTER TABLE "REFERENCIA"."TPRY_CONTACTO_PROVEEDOR" ADD CONSTRAINT "PK01_CTOP_ID" PRIMARY KEY ("CTOP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "REFERENCIA"."TPRY_CONTACTO_PROVEEDOR" MODIFY ("CTOP_TELOFICINA" NOT NULL ENABLE);
  ALTER TABLE "REFERENCIA"."TPRY_CONTACTO_PROVEEDOR" MODIFY ("CTOP_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "REFERENCIA"."TPRY_CONTACTO_PROVEEDOR" MODIFY ("CTOP_APMATERNO" NOT NULL ENABLE);
  ALTER TABLE "REFERENCIA"."TPRY_CONTACTO_PROVEEDOR" MODIFY ("CTOP_APPATERNO" NOT NULL ENABLE);
  ALTER TABLE "REFERENCIA"."TPRY_CONTACTO_PROVEEDOR" MODIFY ("CTOP_NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "REFERENCIA"."TPRY_CONTACTO_PROVEEDOR" MODIFY ("CTOP_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table TPRY_CONTACTO_PROVEEDOR
--------------------------------------------------------

  ALTER TABLE "REFERENCIA"."TPRY_CONTACTO_PROVEEDOR" ADD CONSTRAINT "FK001_CTTO_PROV_ID" FOREIGN KEY ("PROV_ID")
	  REFERENCES "REFERENCIA"."TPRY_PROVEEDORES" ("PROV_ID") ENABLE;
