--------------------------------------------------------
-- Archivo creado  - viernes-abril-04-2014   
--------------------------------------------------------
DROP TABLE "REFERENCIA"."TPRY_OBRAS_PROVEEDOR" cascade constraints;
DROP TABLE "REFERENCIA"."TPRY_PROVEEDORES" cascade constraints;
DROP TABLE "REFERENCIA"."TPRY_TIPO_OBRA" cascade constraints;
--------------------------------------------------------
--  DDL for Table TPRY_OBRAS_PROVEEDOR
--------------------------------------------------------

  CREATE TABLE "REFERENCIA"."TPRY_OBRAS_PROVEEDOR" 
   (	"PROV_ID" NUMBER, 
	"TOBR_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table TPRY_PROVEEDORES
--------------------------------------------------------

  CREATE TABLE "REFERENCIA"."TPRY_PROVEEDORES" 
   (	"PROV_ID" NUMBER, 
	"PROV_RAZON_SOCIAL" VARCHAR2(100 BYTE), 
	"PROV_DOM_FISCAL" VARCHAR2(200 BYTE), 
	"PROV_DOM_CORRESP" VARCHAR2(200 BYTE), 
	"PROV_REGISTRO_ABAST" NUMBER, 
	"PROV_REGISTRO_PROY" NUMBER, 
	"ZPRO_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table TPRY_TIPO_OBRA
--------------------------------------------------------

  CREATE TABLE "REFERENCIA"."TPRY_TIPO_OBRA" 
   (	"TOBR_ID" NUMBER, 
	"TOBR_OBRA" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
REM INSERTING into REFERENCIA.TPRY_OBRAS_PROVEEDOR
SET DEFINE OFF;
Insert into REFERENCIA.TPRY_OBRAS_PROVEEDOR (PROV_ID,TOBR_ID) values (86,1);
Insert into REFERENCIA.TPRY_OBRAS_PROVEEDOR (PROV_ID,TOBR_ID) values (86,2);
Insert into REFERENCIA.TPRY_OBRAS_PROVEEDOR (PROV_ID,TOBR_ID) values (86,3);
Insert into REFERENCIA.TPRY_OBRAS_PROVEEDOR (PROV_ID,TOBR_ID) values (87,1);
Insert into REFERENCIA.TPRY_OBRAS_PROVEEDOR (PROV_ID,TOBR_ID) values (87,2);
Insert into REFERENCIA.TPRY_OBRAS_PROVEEDOR (PROV_ID,TOBR_ID) values (87,3);
Insert into REFERENCIA.TPRY_OBRAS_PROVEEDOR (PROV_ID,TOBR_ID) values (91,3);
Insert into REFERENCIA.TPRY_OBRAS_PROVEEDOR (PROV_ID,TOBR_ID) values (91,5);
--------------------------------------------------------
--  DDL for Index TPRY_OBRAS_PROVEEDOR_PK01
--------------------------------------------------------

  CREATE UNIQUE INDEX "REFERENCIA"."TPRY_OBRAS_PROVEEDOR_PK01" ON "REFERENCIA"."TPRY_OBRAS_PROVEEDOR" ("PROV_ID", "TOBR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table TPRY_OBRAS_PROVEEDOR
--------------------------------------------------------

  ALTER TABLE "REFERENCIA"."TPRY_OBRAS_PROVEEDOR" MODIFY ("TOBR_ID" NOT NULL ENABLE);
  ALTER TABLE "REFERENCIA"."TPRY_OBRAS_PROVEEDOR" MODIFY ("PROV_ID" NOT NULL ENABLE);
  ALTER TABLE "REFERENCIA"."TPRY_OBRAS_PROVEEDOR" ADD CONSTRAINT "TPRY_OBRAS_PROVEEDOR_PK01" PRIMARY KEY ("PROV_ID", "TOBR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TPRY_OBRAS_PROVEEDOR
--------------------------------------------------------

  ALTER TABLE "REFERENCIA"."TPRY_OBRAS_PROVEEDOR" ADD CONSTRAINT "FK001_OBRP_TOBR_ID" FOREIGN KEY ("TOBR_ID")
	  REFERENCES "REFERENCIA"."TPRY_TIPO_OBRA" ("TOBR_ID") ENABLE;
  ALTER TABLE "REFERENCIA"."TPRY_OBRAS_PROVEEDOR" ADD CONSTRAINT "FK002_OBRP_PROV_ID" FOREIGN KEY ("PROV_ID")
	  REFERENCES "REFERENCIA"."TPRY_PROVEEDORES" ("PROV_ID") ENABLE;
