--------------------------------------------------------
-- Archivo creado  - viernes-abril-04-2014   
--------------------------------------------------------
DROP TABLE "REFERENCIA"."TPRY_TIPO_CONVENIO" cascade constraints;
--------------------------------------------------------
--  DDL for Table TPRY_TIPO_CONVENIO
--------------------------------------------------------

  CREATE TABLE "REFERENCIA"."TPRY_TIPO_CONVENIO" 
   (	"TCNV_ID" NUMBER, 
	"TCNV_NOMBRE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
REM INSERTING into REFERENCIA.TPRY_TIPO_CONVENIO
SET DEFINE OFF;
Insert into REFERENCIA.TPRY_TIPO_CONVENIO (TCNV_ID,TCNV_NOMBRE) values (1,'Convenio Importe');
Insert into REFERENCIA.TPRY_TIPO_CONVENIO (TCNV_ID,TCNV_NOMBRE) values (2,'Convenio Plazo');
Insert into REFERENCIA.TPRY_TIPO_CONVENIO (TCNV_ID,TCNV_NOMBRE) values (3,'Convenio Plazo e Importe');
--------------------------------------------------------
--  DDL for Index TGENTIPOCONVENIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "REFERENCIA"."TGENTIPOCONVENIO_PK" ON "REFERENCIA"."TPRY_TIPO_CONVENIO" ("TCNV_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table TPRY_TIPO_CONVENIO
--------------------------------------------------------

  ALTER TABLE "REFERENCIA"."TPRY_TIPO_CONVENIO" ADD CONSTRAINT "PK01_TCNV_ID" PRIMARY KEY ("TCNV_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "REFERENCIA"."TPRY_TIPO_CONVENIO" MODIFY ("TCNV_ID" NOT NULL ENABLE);
