--------------------------------------------------------
-- Archivo creado  - miércoles-abril-23-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TPRY_PROYECTOS
--------------------------------------------------------

  CREATE TABLE "REFERENCIA"."TPRY_PROYECTOS" 
   (	"PROY_ID" NUMBER, 
	"PROY_CARPETA" NUMBER, 
	"EMPR_ID" VARCHAR2(5 BYTE), 
	"PROY_NOMBRE" VARCHAR2(400 BYTE), 
	"PROY_NOMBRE_CORTO" VARCHAR2(200 BYTE), 
	"TOBR_ID" NUMBER, 
	"ORGP_ID" NUMBER, 
	"DIVP_ID" NUMBER, 
	"PROY_FECHA_RECEP_INF" TIMESTAMP (6), 
	"PROY_PRESUPUESTO" NUMBER, 
	"PROY_ELEMENTO_PEP" VARCHAR2(20 BYTE), 
	"PROY_CENTRO_COSTOS" VARCHAR2(200 BYTE), 
	"PROY_SOL_INVERSION" VARCHAR2(1 BYTE), 
	"PROY_FECH_ENTREGA_SAI" TIMESTAMP (6), 
	"PROY_SOLICITUD_SAP" NUMBER, 
	"PROY_FECH_INICIO_ESTIMADO" TIMESTAMP (6), 
	"PROY_FECH_FIN_ESTIMADO" TIMESTAMP (6), 
	"PROY_DURACION_PROY" NUMBER, 
	"PROY_FECH_INICIO_REAL" TIMESTAMP (6), 
	"PROY_FECH_FIN_REAL" TIMESTAMP (6), 
	"EPRY_ID" NUMBER, 
	"PROY_EST_INVITACION" DATE, 
	"PROY_EST_VISITA_OBRA" DATE, 
	"PROY_EST_PREGUNTAS" DATE, 
	"PROY_EST_RESPUESTAS" DATE, 
	"PROY_EST_PROPUESTAS" DATE, 
	"PROY_EST_REVISION_TEC" DATE, 
	"PROY_EST_CHECKLIST_TEC" DATE, 
	"PROY_EST_CARTA_INTENCION" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
REM INSERTING into REFERENCIA.TPRY_PROYECTOS
SET DEFINE OFF;
Insert into REFERENCIA.TPRY_PROYECTOS (PROY_ID,PROY_CARPETA,EMPR_ID,PROY_NOMBRE,PROY_NOMBRE_CORTO,TOBR_ID,ORGP_ID,DIVP_ID,PROY_FECHA_RECEP_INF,PROY_PRESUPUESTO,PROY_ELEMENTO_PEP,PROY_CENTRO_COSTOS,PROY_SOL_INVERSION,PROY_FECH_ENTREGA_SAI,PROY_SOLICITUD_SAP,PROY_FECH_INICIO_ESTIMADO,PROY_FECH_FIN_ESTIMADO,PROY_DURACION_PROY,PROY_FECH_INICIO_REAL,PROY_FECH_FIN_REAL,EPRY_ID,PROY_EST_INVITACION,PROY_EST_VISITA_OBRA,PROY_EST_PREGUNTAS,PROY_EST_RESPUESTAS,PROY_EST_PROPUESTAS,PROY_EST_REVISION_TEC,PROY_EST_CHECKLIST_TEC,PROY_EST_CARTA_INTENCION) values (33,21,'FSRR','CINCO Y CINCO','Diez',2,3,3,to_timestamp('12/04/14 00:00:00.000000000','DD/MM/RR HH24:MI:SS.FF'),20000,'98-55-36-22-75-6-9','4567888ANC','N',to_timestamp('16/05/14 00:00:00.000000000','DD/MM/RR HH24:MI:SS.FF'),987654,to_timestamp('20/05/14 00:00:00.000000000','DD/MM/RR HH24:MI:SS.FF'),to_timestamp('21/05/14 00:00:00.000000000','DD/MM/RR HH24:MI:SS.FF'),26,to_timestamp('02/06/14 00:00:00.000000000','DD/MM/RR HH24:MI:SS.FF'),to_timestamp('04/06/14 00:00:00.000000000','DD/MM/RR HH24:MI:SS.FF'),1,to_date('20/05/14','DD/MM/RR'),to_date('17/05/14','DD/MM/RR'),to_date('20/05/14','DD/MM/RR'),to_date('20/05/14','DD/MM/RR'),to_date('30/05/14','DD/MM/RR'),to_date('20/05/14','DD/MM/RR'),to_date('10/04/14','DD/MM/RR'),to_date('15/10/14','DD/MM/RR'));
--------------------------------------------------------
--  DDL for Index TPRY_PROYECTOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "REFERENCIA"."TPRY_PROYECTOS_PK" ON "REFERENCIA"."TPRY_PROYECTOS" ("PROY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table TPRY_PROYECTOS
--------------------------------------------------------

  ALTER TABLE "REFERENCIA"."TPRY_PROYECTOS" ADD CONSTRAINT "PK01_PROY_ID" PRIMARY KEY ("PROY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "REFERENCIA"."TPRY_PROYECTOS" MODIFY ("PROY_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table TPRY_PROYECTOS
--------------------------------------------------------

  ALTER TABLE "REFERENCIA"."TPRY_PROYECTOS" ADD CONSTRAINT "FK01_PROY_TOBR_ID" FOREIGN KEY ("TOBR_ID")
	  REFERENCES "REFERENCIA"."TPRY_TIPO_OBRA" ("TOBR_ID") ENABLE;
  ALTER TABLE "REFERENCIA"."TPRY_PROYECTOS" ADD CONSTRAINT "FK02_PROY_EMPR_ID" FOREIGN KEY ("EMPR_ID")
	  REFERENCES "REFERENCIA"."TPRY_EMPRESA" ("EMPR_ID") ENABLE;
  ALTER TABLE "REFERENCIA"."TPRY_PROYECTOS" ADD CONSTRAINT "FK03_PROY_DIVP_ID" FOREIGN KEY ("DIVP_ID")
	  REFERENCES "REFERENCIA"."TPRY_DIVISION" ("DIVS_ID") ENABLE;
  ALTER TABLE "REFERENCIA"."TPRY_PROYECTOS" ADD CONSTRAINT "FK04_PROY_ORGP_ID" FOREIGN KEY ("ORGP_ID")
	  REFERENCES "REFERENCIA"."TPRY_ORIGEN_PROYECTO" ("OPRY_ID") ENABLE;
  ALTER TABLE "REFERENCIA"."TPRY_PROYECTOS" ADD CONSTRAINT "FK05_PROY_EPRY_ID" FOREIGN KEY ("EPRY_ID")
	  REFERENCES "REFERENCIA"."TPRY_ESTATUS_PROYECTO" ("EPRY_ID") ENABLE;
