
  CREATE TABLE "REFERENCIA"."TPRY_DOCS_OFICIALES" 
   (	"IDDOCUMENTO" NUMBER(10,0) NOT NULL ENABLE, 
	"FOLIO" VARCHAR2(50 BYTE), 
	"EMPRESA" VARCHAR2(5 BYTE) NOT NULL ENABLE, 
	"FECHAELABORACION" TIMESTAMP (6), 
	"TIPODOCUMENTO" NUMBER(*,0), 
	"IDPROVEEDOR" NUMBER(*,0), 
	"DIRIGIDOA" VARCHAR2(80 BYTE), 
	"PROYECTO" NUMBER(*,0), 
	"ELABORO" NUMBER(*,0), 
	"OBSERVACIONES" VARCHAR2(200 BYTE), 
	 CONSTRAINT "TPRYDOCS_OFICIALES_PK" PRIMARY KEY ("IDDOCUMENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE, 
	 CONSTRAINT "FK01_TPRY_DOCS_OFI_EMPRESA" FOREIGN KEY ("EMPRESA")
	  REFERENCES "REFERENCIA"."TGEN_EMPRESA" ("IDEMPRESA") ENABLE, 
	 CONSTRAINT "FK02_TPRY_DOCS_OFI_TIPODOC" FOREIGN KEY ("TIPODOCUMENTO")
	  REFERENCES "REFERENCIA"."TGEN_TIPO_DOCUMENTO" ("IDTIPODOCUMENTO") ENABLE, 
	 CONSTRAINT "FK03_TPRY_DOCS_OFI_PROYECTO" FOREIGN KEY ("PROYECTO")
	  REFERENCES "REFERENCIA"."TPRY_PROYECTOS" ("IDPROYECTO") ENABLE, 
	 CONSTRAINT "FK04_TPRY_DOCS_OFI_RESP" FOREIGN KEY ("ELABORO")
	  REFERENCES "REFERENCIA"."TPRY_RESPONSABLES" ("IDRESPONSABLE") ENABLE, 
	 CONSTRAINT "FK05_TPRY_DOCS_OFI_PROV" FOREIGN KEY ("IDPROVEEDOR")
	  REFERENCES "REFERENCIA"."TPRY_PROVEEDORES" ("IDPROVEEDOR") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
